# Generated by Django 3.0.6 on 2020-06-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200531_2209'),
    ]

    operations = [

        migrations.RemoveField(
            model_name='note',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='note',
            name='date_expected',
        ),
        migrations.RemoveField(
            model_name='note',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.CharField(default='test', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='is_visible',
            field=models.BooleanField(max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=256),
        ),
    ]
